require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TreasuresController do

  # This should return the minimal set of attributes required to create a valid
  # Treasure. As you add validations to Treasure, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "description" => "MyText" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TreasuresController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all treasures as @treasures" do
      treasure = Treasure.create! valid_attributes
      get :index, {}, valid_session
      assigns(:treasures).should eq([treasure])
    end
  end

  describe "GET show" do
    it "assigns the requested treasure as @treasure" do
      treasure = Treasure.create! valid_attributes
      get :show, {:id => treasure.to_param}, valid_session
      assigns(:treasure).should eq(treasure)
    end
  end

  describe "GET new" do
    it "assigns a new treasure as @treasure" do
      get :new, {}, valid_session
      assigns(:treasure).should be_a_new(Treasure)
    end
  end

  describe "GET edit" do
    it "assigns the requested treasure as @treasure" do
      treasure = Treasure.create! valid_attributes
      get :edit, {:id => treasure.to_param}, valid_session
      assigns(:treasure).should eq(treasure)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Treasure" do
        expect {
          post :create, {:treasure => valid_attributes}, valid_session
        }.to change(Treasure, :count).by(1)
      end

      it "assigns a newly created treasure as @treasure" do
        post :create, {:treasure => valid_attributes}, valid_session
        assigns(:treasure).should be_a(Treasure)
        assigns(:treasure).should be_persisted
      end

      it "redirects to the created treasure" do
        post :create, {:treasure => valid_attributes}, valid_session
        response.should redirect_to(Treasure.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved treasure as @treasure" do
        # Trigger the behavior that occurs when invalid params are submitted
        Treasure.any_instance.stub(:save).and_return(false)
        post :create, {:treasure => { "description" => "invalid value" }}, valid_session
        assigns(:treasure).should be_a_new(Treasure)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Treasure.any_instance.stub(:save).and_return(false)
        post :create, {:treasure => { "description" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested treasure" do
        treasure = Treasure.create! valid_attributes
        # Assuming there are no other treasures in the database, this
        # specifies that the Treasure created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Treasure.any_instance.should_receive(:update).with({ "description" => "MyText" })
        put :update, {:id => treasure.to_param, :treasure => { "description" => "MyText" }}, valid_session
      end

      it "assigns the requested treasure as @treasure" do
        treasure = Treasure.create! valid_attributes
        put :update, {:id => treasure.to_param, :treasure => valid_attributes}, valid_session
        assigns(:treasure).should eq(treasure)
      end

      it "redirects to the treasure" do
        treasure = Treasure.create! valid_attributes
        put :update, {:id => treasure.to_param, :treasure => valid_attributes}, valid_session
        response.should redirect_to(treasure)
      end
    end

    describe "with invalid params" do
      it "assigns the treasure as @treasure" do
        treasure = Treasure.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Treasure.any_instance.stub(:save).and_return(false)
        put :update, {:id => treasure.to_param, :treasure => { "description" => "invalid value" }}, valid_session
        assigns(:treasure).should eq(treasure)
      end

      it "re-renders the 'edit' template" do
        treasure = Treasure.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Treasure.any_instance.stub(:save).and_return(false)
        put :update, {:id => treasure.to_param, :treasure => { "description" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested treasure" do
      treasure = Treasure.create! valid_attributes
      expect {
        delete :destroy, {:id => treasure.to_param}, valid_session
      }.to change(Treasure, :count).by(-1)
    end

    it "redirects to the treasures list" do
      treasure = Treasure.create! valid_attributes
      delete :destroy, {:id => treasure.to_param}, valid_session
      response.should redirect_to(treasures_url)
    end
  end

end
